name: create release

on:
  push:
    branches:
      - production

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Generate release With Semver-tags
        uses: SOLIDSoftworks/semver-tags@v1
        with:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          tag-prefix: 'v'
          default-version: '0.0.1'
